language: python

python:
  - 2.7

install:
  - pip install beautifulsoup4
  - pip install coveralls
  - pip install jsm
  - pip install tweepy

script:
  - nosetests -v --with-coverage -w test/account --cover-package=account

after_success:
  - coveralls
