language: python

python:
  - 2.7

install:
  - pip install BeautifulSoup
  - pip install coveralls
  - pip install jsm
  - pip install lxml
  - pip install tweepy

script:
  - nosetests --with-coverage -v -w test/account

after_success:
  - coveralls
